### ISSUE TITLE
Issues with parenthesis ( ) in library names

### ISSUE THREAD

**Issue by cmaglie** [sparkfun/SparkFun_Serial_Controlled_Motor_Driver_Arduino_Library#1]
As reported in https://github.com/arduino/Arduino/issues/5955.

Please fix it so we can re-add the library to the index!

thanks!

**Comment by marshalltaylorSFE** [comment]
Fixed
New tag:
https://github.com/sparkfun/SparkFun_Serial_Controlled_Motor_Driver_Arduino_Library/tree/V_1.0.1
