### ISSUE TITLE
wire.begin problem

### ISSUE THREAD

**Issue by marshalltaylorSFE** [sparkfun/SparkFun_Serial_Controlled_Motor_Driver_Arduino_Library#2]
On samd21, wire.begin(address) is used to indicate slave device, remove address and test on platforms.

**Comment by Amin173** [comment]
Hi Marshal,
I am using the SparkFun_Serial_Controlled_Motor_Driver_Arduino_Library. I used it with Arduino UNO and it worked perfectly. But when I tried to run it with Sparkfun's SAMD21 Mini, I faced a problem with the myMotorDriver.begin() function. The code stops at this line and doesn't go to the next line. I checked the function definition but I couldn't find whats the problem. May you help me with this? 

Bests,

**Comment by loricrotser** [comment]
Hi! I'd need more information on how you're using the SCMD but on the SamD21, wire.begin is used to indicate a slave device and so would impact your ability to move forward. I found your comment on the SparkFun forums - I'll poke there to see if we can't get more technical information. 

-L
